//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoronaManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoronaManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algeria
        ///Angola
        ///Benin
        ///Botswana
        ///Burkina Faso
        ///Burundi
        ///Cameroon
        ///Cape Verde
        ///Central African Republic
        ///Chad
        ///Comoros
        ///Congo
        ///Democratic Republic of the Congo (Zaire)
        ///Ivory Coast
        ///Djibouti
        ///Egypt
        ///Equatorial Guinea
        ///Eritrea
        ///Ethiopia
        ///Gabon
        ///Gambia
        ///Ghana
        ///Guinea
        ///Guinea-Bissau
        ///Kenya
        ///Lesotho
        ///Liberia
        ///Libya
        ///Madagascar
        ///Malawi
        ///Mali
        ///Mauritania
        ///Mauritius
        ///Morocco
        ///Mozambique
        ///Namibia
        ///Niger
        ///Nigeria
        ///Rwanda
        ///São Tomé and Príncipe
        ///Senegal
        ///Seychelles
        ///Sierra Leone
        ///Somalia
        ///South Africa
        ///South Sudan
        ///S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Africa {
            get {
                return ResourceManager.GetString("Africa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan
        ///Armenia
        ///Azerbaijan
        ///Bahrain
        ///Bangladesh
        ///Bhutan
        ///Brunei
        ///Cambodia
        ///China
        ///Cyprus
        ///East Timor
        ///Georgia
        ///Hong Kong
        ///India
        ///Indonesia
        ///Iran
        ///Iraq
        ///Israel
        ///Japan
        ///Jordan
        ///Kazakhstan
        ///Kuwait
        ///Kyrgyzstan
        ///Laos
        ///Lebanon
        ///Malaysia
        ///Maldives
        ///Mongolia
        ///Myanmar
        ///Nepal
        ///North Korea
        ///Oman
        ///Pakistan
        ///Palestine
        ///Philippines
        ///Qatar
        ///Russia
        ///Saudi Arabia
        ///Singapore
        ///S. Korea
        ///Sri Lanka
        ///Syria
        ///Tajikistan
        ///Thailand
        ///Turkey
        ///Turkmenistan
        ///Taiwan
        ///UAE
        ///Uzbekistan
        ///Vietnam
        ///Yemen.
        /// </summary>
        internal static string Asia {
            get {
                return ResourceManager.GetString("Asia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albania
        ///Andorra
        ///Austria
        ///Belarus
        ///Belgium
        ///Bosnia and Herzegovina
        ///Bulgaria
        ///Croatia
        ///Czechia
        ///Denmark
        ///Estonia
        ///Faeroe Islands
        ///Finland
        ///France
        ///Germany
        ///Greece
        ///Gibraltar
        ///Hungary
        ///Iceland
        ///Ireland
        ///Italy
        ///Kosovo
        ///Latvia
        ///Liechtenstein
        ///Lithuania
        ///Luxembourg
        ///North Macedonia
        ///Malta
        ///Moldova
        ///Monaco
        ///Montenegro
        ///Netherlands
        ///Norway
        ///Poland
        ///Portugal
        ///Romania
        ///Russia
        ///San Marino
        ///Serbia
        ///Slovakia
        ///Slovenia
        ///Spain
        ///Sweden
        ///Switzerland
        ///Ukraine
        ///UK
        ///Vatican City.
        /// </summary>
        internal static string Europe {
            get {
                return ResourceManager.GetString("Europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antigua and Barbuda
        ///Anguilla
        ///Aruba 
        ///The Bahamas
        ///Barbados
        ///Belize
        ///Bermuda
        ///Bonaire
        ///British Virgin Islands
        ///Canada
        ///Cayman Islands
        ///Clipperton Island
        ///Costa Rica
        ///Cuba
        ///Curaçao
        ///Dominica
        ///Dominican Republic
        ///El Salvador
        ///Greenland
        ///Grenada
        ///Guadeloupe
        ///Guatemala
        ///Haiti
        ///Honduras
        ///Jamaica
        ///Martinique
        ///Mexico
        ///Montserrat
        ///Navassa Island
        ///Nicaragua
        ///Panama
        ///Puerto Rico
        ///Saba
        ///Saint Barthelemy
        ///Saint Kitts and Nevis
        ///Saint Lucia
        ///Saint Martin
        ///Saint Pierre and Miquelon
        ///Saint Vincent and the Grenadines
        ///Sin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string North_America {
            get {
                return ResourceManager.GetString("North_America", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia
        ///Federated States of Micronesia
        ///Fiji
        ///Guam
        ///Kiribati
        ///Marshall Islands
        ///Nauru
        ///New Zealand
        ///Palau
        ///Papua New Guinea
        ///Samoa
        ///Solomon Islands
        ///Tonga
        ///Tuvalu
        ///Vanuatu
        ///Flores
        ///Lombok
        ///Melanesia
        ///New Caledonia
        ///New Guinea
        ///Sulawesi
        ///Sumbawa
        ///Timor.
        /// </summary>
        internal static string Oceania {
            get {
                return ResourceManager.GetString("Oceania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentina
        ///Aruba
        ///Bolivia
        ///Brazil
        ///Chile
        ///Colombia
        ///Ecuador
        ///Falkland Islands
        ///French Guiana
        ///Guyana
        ///Paraguay
        ///Peru
        ///South Georgia and the South Sandwich Islands
        ///Suriname
        ///St. Barth
        ///Uruguay
        ///Venezuela.
        /// </summary>
        internal static string South_America {
            get {
                return ResourceManager.GetString("South_America", resourceCulture);
            }
        }
    }
}
